In [7]:
import numpy as np
from scipy.linalg import eig

In [8]:
# 成对比较矩阵
A = np.array([
    [1, 1/5, 1/2, 1/3, 1/4, 1/5],
    [5, 1, 5, 1/3, 5, 1/2],
    [2, 1/5, 1, 1/6, 2, 1/3],
    [3, 3, 6, 1, 7, 5],
    [4, 1/5, 1/2, 1/7, 1, 1/5],
    [5, 2, 3, 1/5, 5, 1]
])
B = np.array([
    [1, 1/6, 1, 1/4, 3, 1],
    [6, 1, 2, 1, 3, 1],
    [1, 1/2, 1, 2, 3, 1/2],
    [4, 1, 1/2, 1, 5, 1],
    [1/3, 1/3, 1/3, 1/5, 1, 1/5],
    [1, 1, 2, 1, 5, 1]
])
C = np.array([
    [1, 1/6, 1/2, 1/6, 1, 3],
    [6, 1, 3, 5, 9, 9],
    [2, 1/3, 1, 3, 9, 5],
    [6, 1/5, 1/3, 1, 5, 1],
    [1, 1/9, 1/9, 1/5, 1, 2],
    [1/3, 1/9, 1/5, 1, 1/2, 1]
])
D = np.array([
    [1, 1/7, 1/5, 1/5, 1/4, 1/2],
    [7, 1, 4, 1, 5, 5],
    [5, 1/4, 1, 1/5, 3, 3],
    [5, 1, 5, 1, 5, 5],
    [4, 1/5, 1/3, 1/5, 1, 1],
    [2, 1/5, 1/3, 1/5, 1, 1]
])

In [9]:
# 计算平均值
X = (A + B + C + D) / 4
X

array([[1.        , 0.16904762, 0.55      , 0.2375    , 1.125     ,
        1.175     ],
       [6.        , 1.        , 3.5       , 1.83333333, 5.5       ,
        3.875     ],
       [2.5       , 0.32083333, 1.        , 1.34166667, 4.25      ,
        2.20833333],
       [4.5       , 1.3       , 2.95833333, 1.        , 5.5       ,
        3.        ],
       [2.33333333, 0.21111111, 0.31944444, 0.18571429, 1.        ,
        0.85      ],
       [2.08333333, 0.82777778, 1.38333333, 0.6       , 2.875     ,
        1.        ]])

In [10]:
# 计算特征向量和特征值
eigenvalues, eigenvectors = eig(X)
eigenvalues, eigenvectors

(array([ 8.10889530e+00+0.j        , -4.03192666e-03+0.51772283j,
        -4.03192666e-03-0.51772283j, -6.38337795e-01+0.55084863j,
        -6.38337795e-01-0.55084863j, -8.24155856e-01+0.j        ]),
 array([[-0.12782961+0.j        , -0.00289873-0.05264266j,
         -0.00289873+0.05264266j,  0.03179553+0.16543449j,
          0.03179553-0.16543449j,  0.03856321+0.j        ],
        [-0.67315119+0.j        ,  0.76873467+0.j        ,
          0.76873467-0.j        ,  0.70806471+0.j        ,
          0.70806471-0.j        , -0.38075781+0.j        ],
        [-0.34416005+0.j        , -0.20280094+0.31851857j,
         -0.20280094-0.31851857j, -0.47065529+0.33639361j,
         -0.47065529-0.33639361j,  0.62834653+0.j        ],
        [-0.56319717+0.j        ,  0.34465085+0.19378205j,
          0.34465085-0.19378205j,  0.23193996+0.00449336j,
          0.23193996-0.00449336j, -0.6383135 +0.j        ],
        [-0.12574921+0.j        , -0.24879165-0.10954668j,
         -0.24879165+0.109546

In [11]:
# 找到最大的特征值及其对应的特征向量
max_eigenvalue_index = np.argmax(eigenvalues)
max_eigenvalue_vector = eigenvectors[:, max_eigenvalue_index]
max_eigenvalue_index, max_eigenvalue_vector

(0,
 array([-0.12782961+0.j, -0.67315119+0.j, -0.34416005+0.j, -0.56319717+0.j,
        -0.12574921+0.j, -0.28120637+0.j]))

In [12]:
# 归一化特征向量，得到权重向量
weights = max_eigenvalue_vector / np.sum(max_eigenvalue_vector)
weights

array([0.06043114-0.j, 0.31823062-0.j, 0.16270084-0.j, 0.26625012-0.j,
       0.05944764-0.j, 0.13293964-0.j])